export const CommunityPageEvents = [
  {
    img: "./walk1.jpeg",
    title: "Stanmer Walk and Chat",
    description: "event description here...",
    date: "July 7th",
    time: "13:30",
    attendees: ["Samii", "Sami", "Isaac", "Hilda", "Jack", "Safiyah", "Jordan"],
  },
  {
    img: "./walk2.jpeg",
    title: "Foraging in Ashdown Forest",
    description: "Join experienced forager Derek and find some mushrooms",
    date: "August 29th",
    time: "09:00",
    attendees: ["Hilda", "Jack", "Isaac", "Eric"],
  },
  {
    img: "./walk3.jpeg",
    title: "Kingston Early Dog Social",
    description: "event description here...",
    date: "July 15th",
    time: "07:30",
    attendees: [
      "Alan",
      "Jordan",
      "Samii",
      "Sami",
      "Isaac",
      "Hilda",
      "Jack",
      "Safiyah",
      "Jordan",
    ],
  },
  {
    img: "./walk1.jpeg",
    title: "Coffee, Chat and Walk",
    description: "event description here...",
    date: "July 12th",
    time: "08:30",
    attendees: ["Safiyah", "Jack", "Isaac", "Hilda", "Debbie"],
  },
  {
    img: "./walk2.jpeg",
    title: "Lake Loop",
    description: "event description here...",
    date: "July 23rd",
    time: "17:30",
    attendees: ["Bryony", "Sami", "Isaac", "James", "Hilda", "Jack"],
  },
  {
    img: "./walk3.jpeg",
    title: "Summer Evening Park Stroll",
    description: "event description here...",
    date: "July 5th",
    time: "20:30",
    attendees: [
      "Jordan",
      "Sami",
      "Isaac",
      "Hilda",
      "Jack",
      "Bryony",
      "Safiyah",
      "Jordan",
      "Abdi",
      "Toni",
      "Guy",
    ],
  },
];
