export const CommunityPageEvents = [{
    img: './walk1.jpeg',
    title: '',
    description: 'event description here...',
    date: '',
    time:'',
    attendees: '',
},
{
    img: './walk1.jpeg',
    title: '',
    description: 'event description here...',
    date: '',
    time:'',
    attendees: '',
}, {   img: './walk1.jpeg',
title: '',
description: 'event description here...',
date: '',
time:'',
attendees: '',
},
]