export const CommunityPageEvents = [
{
    img: './walk1.jpeg',
    title: 'Stanmer Walk and Chat',
    description: 'event description here...',
    date: 'July 7th',
    time:'13:30',
    attendees: 3,
},
{
    img: './walk2.jpeg',
    title: 'Foraging in Ashdown Forest',
    description: 'Join experienced forager Derek and find some mushrooms',
    date: 'August 29th',
    time:'09:00',
    attendees: 14,
}, 
{   
    img: './walk3.jpeg',
    title: 'Kingston Early Dog Social',
    description: 'event description here...',
    date: 'July 15th',
    time:'07:30',
    attendees: 2,
},
{
    img: './walk1.jpeg',
    title: 'Coffee, Chat and Walk',
    description: 'event description here...',
    date: 'July 12th',
    time:'08:30',
    attendees: '6',
},
{
    img: './walk2.jpeg',
    title: 'Lake Loop',
    description: 'event description here...',
    date: 'July 23rd',
    time:'17:30',
    attendees: '8',
},
{
    img: './walk3.jpeg',
    title: 'Summer Evening Park Stroll',
    description: 'event description here...',
    date: 'July 5th',
    time:'20:30',
    attendees: '9',
}
]